config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  resources :login
  resources :home
  resources :team
  resources :contact
  resources :welcome
  resources :gossip do
    resources :comments
  end
  resources :user
  resources :city
  resources :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    validates_associated :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
    validates_presence_of :content
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates_presence_of :title, :content
    has_many :comments
    validates_associated :comments
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :gossips
    validates_associated :gossips
    has_many :comments
    validates_associated :comments
    validates_presence_of :first_name, :last_name, :email
    has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params['id'])
    @user = User.where(city_id: params['id']).order(created_at: :desc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def show
    end
  
    def index
    end
  
    def new
      @comment = Comment.new
    end
  
    def create
      comment = Comment.new(content: params[:content], user_id: session[:user_id], gossip_id: params[:id])
      if comment.save
        flash[:success] = "commentaire envoyer"
        redirect_to gossip_path(params[:gossip_id])
      else
        flash[:alert] = "champ vide"
        redirect_to gossip_path(params[:gossip_id])
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:success] = "commentaire supprimer"
      redirect_to gossip_path(params[:gossip_id])
    else
      flash[:alert] = "commentaire n a pas ete supprimer"
      redirect_to gossip_path(params[:gossip_id])
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def index
    @gossip = Gossip.all
  end

  def new
    as_to_login
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
    if gossip.save
      flash[:success] = "le potin a ete creer"
      redirect_to home_index_path
    else
      flash[:alert] = "le potin n a pas ete rempli"
      render 'new'
    end
  end

  def edit
    as_to_login
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.title == params[:gossip][:title] && @gossip.content == params[:gossip][:content]
      flash[:alert] = "pas de modification apporter"
      redirect_to @gossip
    elsif @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content])
      flash[:success] = "potin mis a jour"
      redirect_to @gossip
    else
      flash[:alert] = "le potin n a pas ete mis a jour"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      flash[:success] = "potin supprimer"
      redirect_to gossip_index_path
    else
      flash[:alert] = "le potin n a pas ete supprimer"
      redirect_to @gossip
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
  def index
    @gossip = Gossip.last(3)
    @user = User.last(3)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to home_index_path
        else
            flash[:alert] = 'mauvais email ou mdp'
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end

  def index
  end

  def new
    @user = User.new
    @city = City.all
  end

  def create 
    user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password])
    if user.save
      flash[:success] = "nouvelle utilisateur creer, veuillez vous connecter"
      redirect_to new_session_path
    else
      flash[:alert] = "compte n a pas ete creer"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/contact/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">Contact</h1>
        <p>formulaire pour nous contacer</p>
        <p>remplir le formulaire avec email pour que nous puissions vous repondre</p>
        </div>
      </div>

app/views/contact/show.html.erb
    <br/><br/><br/>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">Contact</h1>
        <p>formulaire pour nous contacer</p>
        <p>remplir le formulaire avec email pour que nous puissions vous repondre</p>
        </div>
      </div>

app/views/home/index.html.erb
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">The Gossip World</h1> 
        <button type="button" class="btn btn-primary"><%=link_to "Ajouter un potin", new_gossip_path, class: "text-white text-decoration-none"%></button>
        </div>
      </div>

<main class="container">
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Derniers potins</h6>
        <% @gossip.each do|g|%>
            <h6 class="mt-2"><%= g.title%><small> date : <%= g.created_at%></small></h6>
          <div class="media text-muted">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">Auteur : <%=link_to "#{g.user.first_name} #{g.user.last_name}", user_path(g.user.id)%></strong>
           <%= g.content.truncate(100)%>
           <%= link_to "suite", gossip_path(g.id) %>
            </p>
          </div>
          <%end%>
          <small class="d-block text-right mt-3">
            <%= link_to 'Tous', gossip_index_path%>
          </small>
        </div>
  <hr>
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Suggestions</h6>
        <% @user.each do |u|%>
        <div class="media text-muted pt-3">
          <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <div class="d-flex justify-content-between align-items-center w-100">
              <strong class="text-gray-dark"><%= u.first_name%> <%= u.last_name%></strong>
              <%= link_to "Fiche", user_path(u.id)%>
            </div>
            <span class="d-block">Nombre de potins : <%=u.gossips.size%></span>
          </div>
        </div>
        <%end%>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script src="offcanvas.js"></script>
  

<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32" preserveAspectRatio="none" style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;"><defs><style type="text/css"></style></defs><text x="0" y="2" style="font-weight:bold;font-size:2pt;font-family:Arial, Helvetica, Open Sans, sans-serif">32x32</text></svg></body>

app/views/home/show.html.erb
<br/>
<br/>
<br/>
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">Acceuil</h1>
        <p>consulter tout les potins</p>
        <p>pour acceder a la page d un potin clique sur son blue title</p>
        </div>
      </div>
      
      <div class="container">
        <!-- Example row of columns -->
        <div class="row d-flex justify-content-around">
            <% @gossips.each do |g| %>
            <div class="col-md-5 border border-primary shadow p-3 mb-5 bg-white rounded">
                <h3><%=link_to "#{g.title}", gossip_path(g.id)%></h3>
                <p><%=g.content %></p>
                <p>auteur : <%=g.user.last_name %></p>
            </div>
            <% end %>
            
        </div>

        <hr>

      </div> <!-- /container -->
        
  </main>

app/views/session/new.html.erb
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-3 text-primary">Login</h1> 
       </div>
      </div>
        <div class="container text-center">
            <div class="login-form">
                <form action= <%= session_index_path %> method="POST">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" id="email" class="form-control" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label>Mot de passe</label>
                        <input type="text" id="password" class="form-control" name="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary">Login</button>
                    <%= link_to "Signin", new_user_path, class: 'btn btn-primary'%>
                </form>
            </div>
        </div>

app/views/team/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-3 text-primary">Team</h1>
            <p>a propos de nous</p>
            <p>On te raconte notre vie</p>
        </div>
    </div>

app/views/team/show.html.erb
    <br/><br/><br/>
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-3 text-primary">Team</h1>
            <p>a propos de nous</p>
            <p>On te raconte notre vie</p>
        </div>
    </div>