config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  resources :login
  resources :home
  resources :team
  resources :contact
  resources :welcome
  resources :gossip do
    resources :comments
  end
  resources :user
  resources :city
  resources :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    validates_associated :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
    validates_presence_of :content
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates_presence_of :title, :content
    has_many :comments
    validates_associated :comments
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :gossips
    validates_associated :gossips
    has_many :comments
    validates_associated :comments
    validates_presence_of :first_name, :last_name, :email
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def as_to_login
        if session[:user_id] == nil
            redirect_to new_session_path
        end
    end
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params['id'])
    @user = User.where(city_id: params['id']).order(created_at: :desc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def show
    end
  
    def index
    end
  
    def new
      @comment = Comment.new
    end
  
    def create
      comment = Comment.new(content: params[:content], user_id: session[:user_id], gossip_id: params[:id])
      if comment.save
        flash[:success] = "commentaire envoyer"
        redirect_to gossip_path(params[:gossip_id])
      else
        flash[:alert] = "champ vide"
        redirect_to gossip_path(params[:gossip_id])
      end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      flash[:success] = "commentaire supprimer"
      redirect_to gossip_path(params[:gossip_id])
    else
      flash[:alert] = "commentaire n a pas ete supprimer"
      redirect_to gossip_path(params[:gossip_id])
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def index
    @gossip = Gossip.all
  end

  def new
    as_to_login
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
    if gossip.save
      flash[:success] = "le potin a ete creer"
      redirect_to home_index_path
    else
      flash[:alert] = "le potin n a pas ete rempli"
      render 'new'
    end
  end

  def edit
    as_to_login
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.title == params[:gossip][:title] && @gossip.content == params[:gossip][:content]
      flash[:alert] = "pas de modification apporter"
      redirect_to @gossip
    elsif @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content])
      flash[:success] = "potin mis a jour"
      redirect_to @gossip
    else
      flash[:alert] = "le potin n a pas ete mis a jour"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      flash[:success] = "potin supprimer"
      redirect_to gossip_index_path
    else
      flash[:alert] = "le potin n a pas ete supprimer"
      redirect_to @gossip
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
  def index
    @gossip = Gossip.last(3)
    @user = User.last(3)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to home_index_path
        else
            flash[:alert] = 'mauvais email ou mdp'
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to new_session_path
    end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end

  def index
  end

  def new
    @user = User.new
    @city = City.all
  end

  def create 
    user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password])
    if user.save
      flash[:success] = "nouvelle utilisateur creer, veuillez vous connecter"
      redirect_to new_session_path
    else
      flash[:alert] = "compte n a pas ete creer"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/show.html.erb
  <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary"><%= @city.name%></h1>
        </div>
      </div>

      <main class="container">
      <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">liste des potins ecrit pour cette ville</h6>
        <% @user.each do|u|%>
            <% u.gossips.each do |g|%>
            <h6 class="mt-2"><%= g.title%><small> date : <%= g.created_at%></small></h6>
          <div class="media text-muted">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">Auteur : <%=link_to "#{u.first_name} #{u.last_name}", user_path(u.id)%></strong>
           <%= g.content.truncate(100)%>
           <%= link_to "suite", gossip_path(g.id) %>
            </p>
          </div>
          <%end%>
          <%end%>
        </div>
        </main>

app/views/gossip/edit.html.erb
<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-3 text-primary"><%= @gossip.title%></h1>
    </div>
</div>

<div class="container text-center">
<%= form_for @gossip do |g| %>
  <%= g.label 'titre' %><br>
  <%= g.text_field :title %><br>

  <%= g.label 'potin' %><br>
  <%= g.text_field :content %><br>

  <%= g.submit "valider" %>
<% end %>

app/views/gossip/index.html.erb
<main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary">Acceuil</h1>
        <p>consulter tout les potins</p>
        <p>pour acceder a la page d un potin clique sur son blue title</p>
        </div>
      </div>
      
      <div class="container">
        <!-- Example row of columns -->
        <div class="row d-flex justify-content-around">
            <% @gossip.each do |g| %>
            <div class="col-md-5 border border-primary shadow p-3 mb-5 bg-white rounded">
                <h3><%=link_to "#{g.title}", gossip_path(g.id)%></h3>
                <p><%=g.content %></p>
                <p>auteur : <%=g.user.last_name %></p>
                <p>c : <%= g.comments.size%></p>
            </div>
            <% end %>
            
        </div>

        <hr>

      </div> <!-- /container -->
        
  </main>

app/views/gossip/new.html.erb
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-3 text-primary">Super Potin in coming</h1>
            <p>fais passer un message</p>
        </div>
    </div>
<div class="container text-center">
    <form action= <%= gossip_index_path %> method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group">
            <input type="text" id="title" class="form-control" name="title" placeholder="titre">
        </div>
        <div class="form-group">
            <textarea id="content" class="form-control" name="content" placeholder="potin"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Valider</button>
        </div>
    </form>
</div>

app/views/gossip/show.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-3 text-primary"><%= @gossip.title%></h1>
        <h3>de <%=link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id)%><h3>
    </div>
</div>
<div class="container text-center">
    <p>potin : <%=@gossip.content%></p>
    <p>date : <%= @gossip.created_at%></p>
    <% if session[:user_id] == @gossip.user.id %>
        <p><%= link_to "edit", edit_gossip_path%></p>
        <p><%= link_to "supprimer", gossip_path(@gossip.id), method: 'delete'%>
    <%end%>
</div>
<hr>
<div class="container">
    <p>commentaires : </p>
    <% @gossip.comments.each do |c| %>
        <p>de : <%= c.user.first_name%> <%= c.user.last_name%></p>
        <p>=> <%= c.content%></p>
        <% if session[:user_id] == c.user.id %>
            <%= link_to "supprimer", gossip_comment_path(@gossip.id, c.id), method: 'delete'%>
        <% end %>
    <%end%>
    <%if session[:user_id] != nil %>
        <%= form_tag(gossip_comments_path(@gossip.id)) do %>
            <%= label_tag 'Ajouter un commentaire' %>
            <%= text_field_tag :content%>
            <%= hidden_field_tag :id, params[:id] %>
            <br /> <br />
            <!-- L'auteur est renseigné dans le create -->
            <%= submit_tag "Envoi", class: 'btn btn-success' %>
        <%end%>
    <%end%>
</div>

app/views/user/new.html.erb
    <div class="jumbotron">
        <div class="container text-center">
            <h1 class="display-3 text-primary">Creer un compte</h1>
            <p>remplie les champs</p>
        </div>
    </div>
    <div class="container text-center">
    <form action= <%= user_index_path %> method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group">
            <input type="text" id="first_name" class="form-control" name="first_name" placeholder="prenom">
        </div>
        <div class="form-group">
            <input type="text" id="last_name" class="form-control" name="last_name" placeholder="nom">
        </div>
        <div class="form-group">
            <input type="text" id="email" class="form-control" name="email" placeholder="email">
        </div>
        <div class="form-group">
            <input type="text" id="password" class="form-control" name="password" placeholder="mot de passe">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Valider</button>
        </div>
    </form>
</div>

app/views/user/show.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <div class="container text-center">
        <h1 class="display-3 text-primary"><%= @user.first_name%> <%= @user.last_name%></h1>
        <p>profil</p>
        <p>toute les infos sur cette auteur</p>
        </div>
      </div>
      <div class="text-center">
        <p>email : <%=@user.email%></p>
        <p>age : <%=@user.age%></p>
        <p>ville : <%=
            if @user.city == nil 
                "pas de ville associer"
            else
                link_to @user.city.name, city_path(@user.city_id)
            end
            %></p>
        <p>description : <%=
            if @user.description == nil
                "pas encore de description"
            else
                @user.description
            end
        %></p>
        <p>Ses potins : 
        <% @user.gossips.each do |g|%>
            <%= link_to g.title, gossip_path(g.id)%> 
        <%end%>
        </p>
        </div>