config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  resources :login
  resources :home
  resources :team
  resources :contact
  resources :welcome
  resources :gossip do
    resources :comments
  end
  resources :user
  resources :city
  resources :session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
    validates_associated :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
    validates_presence_of :content
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates_presence_of :title, :content
    has_many :comments
    validates_associated :comments
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city, optional: true
    has_many :gossips
    validates_associated :gossips
    has_many :comments
    validates_associated :comments
    validates_presence_of :first_name, :last_name, :email
    has_secure_password
end

app/controllers/city_controller.rb
class CityController < ApplicationController
  def show
    @city = City.find(params['id'])
    @user = User.where(city_id: params['id']).order(created_at: :desc)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
    @gossip = Gossip.find(params[:id])
  end

  def index
    @gossip = Gossip.all
  end

  def new
    as_to_login
    @gossip = Gossip.new
  end

  def create
    gossip = Gossip.new(title: params[:title], content: params[:content], user_id: session[:user_id])
    if gossip.save
      flash[:success] = "le potin a ete creer"
      redirect_to home_index_path
    else
      flash[:alert] = "le potin n a pas ete rempli"
      render 'new'
    end
  end

  def edit
    as_to_login
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.title == params[:gossip][:title] && @gossip.content == params[:gossip][:content]
      flash[:alert] = "pas de modification apporter"
      redirect_to @gossip
    elsif @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content])
      flash[:success] = "potin mis a jour"
      redirect_to @gossip
    else
      flash[:alert] = "le potin n a pas ete mis a jour"
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    if @gossip.destroy
      flash[:success] = "potin supprimer"
      redirect_to gossip_index_path
    else
      flash[:alert] = "le potin n a pas ete supprimer"
      redirect_to @gossip
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

  end
  def index
    @gossip = Gossip.last(3)
    @user = User.last(3)
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
    def show
    end

    def index
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params['id'])
  end

  def index
  end

  def new
    @user = User.new
    @city = City.all
  end

  def create 
    user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password])
    if user.save
      flash[:success] = "nouvelle utilisateur creer, veuillez vous connecter"
      redirect_to new_session_path
    else
      flash[:alert] = "compte n a pas ete creer"
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  </head>

  <body>
    <br/>
    <br/>
    <% if flash[:success] %>
      <div class="alert alert-success" role="alert"><%= flash[:success] %></div>
    <%end%>
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
    <%end%>
    <%= yield %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <%= link_to "The Gossip Project", home_index_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Contact", contact_index_path, class:'nav-link'%>
        </li>
        <li class="nav-item">
          <%= link_to "Team", team_index_path, class:'nav-link' %>
        </li>
      </ul>
      <div class="mr-0">
        <%= if session[:user_id] == nil
          link_to "login/signin", new_session_path, class:'nav-link'
        else
            link_to "logout", session_path(session[:user_id]), method: :delete, class:'nav-link'
          end %>
      </div>
    </div>
  </nav>
  </body>
</html>